" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim74/vimrc_example.vim or the vim manual
" and configure vim to your own liking!
autocmd FileType text setlocal wrap textwidth=78
autocmd FileType c,cpp map <buffer> <leader><space> :w<cr>:make<cr>
autocmd FileType c set makeprg=gcc\ %\ -Wall\ -o\ %<
autocmd FileType cpp set makeprg=g++\ %\ -Wall\ -o\ %<
"exclude VI
set nocompatible
"no backup
set nobackup
set nowb

set nu
set ruler
set showcmd

"set color theme
colorscheme ron
if &t_Co >1
       syntax on
endif
set laststatus=1
set autowrite
set cursorline
set foldenable
set foldmethod=indent
set showmatch
set matchtime=1

filetype indent plugin on  
set shiftwidth=3

set ww=b,s

"set the search mode
set incsearch
set hlsearch

set scrolloff=3

"copy the whole content by Ctrl-A
map <C-A> <Esc>ggvGy<Esc>

"compile the file specified by type
map <F5> :call CompileRunGcc()<CR>
func! CompileRunGcc()
       exec "w"
       if &filetype == 'c'
               exec "!gcc % -o %<"
               exec "! ./%<"
       elseif &filetype == 'cpp'
               exec "!g++ % -o %<"
               exec "! ./%<"
       elseif &filetype == 'py'
               exec "!python %"
               exec "!python %<"
       elseif &filetype =='html'
	       exec "!firefox %"
       elseif &filetype =='js'
	       exec "!firefox %<.html"
       endif
endfunc

set autoread
set completeopt=preview,menu
set clipboard+=unnamed
set history=1000

"set the locale
set enc=utf-8
set fencs=utf-8,gb18030,gbk,gb2312,cp936

"set the indent way of language
set smartindent
set backspace=2

"set the mouse function
set mouse=a
set selection=exclusive
set selectmode=mouse,key

"some settings for vim-latexsuite
set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"

"some settings for vim-taglist
let Tlist_Auto_Open=1
let Tlist_Use_SingleClick=1
let Tlist_Process_File_Always=1
let Tlist_Show_One_File=0
let Tlist_File_Fold_Auto_Close=1
nnoremap <silent> <F8> :TlistToggle<CR>
noremap <silent> <F9> :BufExplorer<CR>
